branches:
  only:
  - master
  - dev
language: node_js
node_js:
- 12.2.0
before_script:
- node --version
- npm --version
script:
- cd $TRAVIS_BUILD_DIR/src/fire-portfolio
- npm install
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: qIlmmdk21Jrhgzumt8eVLc5XSGLcxllDilwOcUSkemmf41N9ODEfsy5sv1569ky6Dz5k0SPtF3sOEMyg+Xwstc53Ekk7vFO+UaeNpymd3DWaUamuTy+C6iGtWiVzFbNNx8cUFr3NZ7k+SXgpNugQB4qHW/VZGCkDrwsKvIVZrHBXhDS4ms12c4BN8STobI1L5g5VK/1vB+vvLkwPku7nhgIS97/JyQshqqSE2WLeUjDXpkL7C85JNLbnTY/NsM2MtlQUgFj31CyR2yh0jmm/KrE8aQg1jgJZloTk0cY5VBjbUuc2AhK4MEvlUYSRZxB+OiVIOtE5WcrWpJScZm/3E55592TM+0Qcz4Nm6HtCBT8uhWQfQ5JEbNPBlv3OCe7EWJnxQtmqFhRFBg0hUea66pwo9vVczU6UMOTx9zIktytjyn+VwacWBz7ctdtXizNxv4+pmZHxLhHlndk0Gjrl6iLuSAKkjfzFpO2ArxG4eF/TMrIlF01/PEZMbBMQYaWG2CnRiRQSK+TlFshLu8JYdjVt2lvYDyAPxQdwt5+1t0kRGu5Z/o0jW/qTMxxgTVWADftFH3QEDS/do4ZhjAG3f5XbzJ/HdEJgw2oyJ9nsJGNeQQJW2RHciFMv+tZrPQjChVJ4Wo9vQ716b2nEQ3HqxRcLTellgoqHyvJVje9nAu0=
  app: fire-breathing-app
  on:
    repo: LesegoGomolemo/2019_IMY320_FireBreathingRubberDuckies
env:
  global:
    secure: qIlmmdk21Jrhgzumt8eVLc5XSGLcxllDilwOcUSkemmf41N9ODEfsy5sv1569ky6Dz5k0SPtF3sOEMyg+Xwstc53Ekk7vFO+UaeNpymd3DWaUamuTy+C6iGtWiVzFbNNx8cUFr3NZ7k+SXgpNugQB4qHW/VZGCkDrwsKvIVZrHBXhDS4ms12c4BN8STobI1L5g5VK/1vB+vvLkwPku7nhgIS97/JyQshqqSE2WLeUjDXpkL7C85JNLbnTY/NsM2MtlQUgFj31CyR2yh0jmm/KrE8aQg1jgJZloTk0cY5VBjbUuc2AhK4MEvlUYSRZxB+OiVIOtE5WcrWpJScZm/3E55592TM+0Qcz4Nm6HtCBT8uhWQfQ5JEbNPBlv3OCe7EWJnxQtmqFhRFBg0hUea66pwo9vVczU6UMOTx9zIktytjyn+VwacWBz7ctdtXizNxv4+pmZHxLhHlndk0Gjrl6iLuSAKkjfzFpO2ArxG4eF/TMrIlF01/PEZMbBMQYaWG2CnRiRQSK+TlFshLu8JYdjVt2lvYDyAPxQdwt5+1t0kRGu5Z/o0jW/qTMxxgTVWADftFH3QEDS/do4ZhjAG3f5XbzJ/HdEJgw2oyJ9nsJGNeQQJW2RHciFMv+tZrPQjChVJ4Wo9vQ716b2nEQ3HqxRcLTellgoqHyvJVje9nAu0=
